/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import


export {}
declare global {
  const ElMessage: typeof import('element-plus')['ElMessage']
  const ElNotification: typeof import('element-plus')['ElNotification']
  const ElMessageBox: typeof import('element-plus')['ElMessageBox']
}


//此文件用来解决上述element组件自动引入报错问题