/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}


//此文件用来解决http.ts文件中ElNotification报错